/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/first-pc.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


export function FirstPc(props) {
  const { nodes, materials } = useGLTF("./models/first-pc.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 2.05 * Math.PI]} castShadow>
        <mesh geometry={nodes.computer_1.geometry} material={materials.COM1} />
        <mesh
          geometry={nodes.computer_2.geometry}
          material={materials["RED PLASTIC1"]}
        />
        <mesh
          geometry={nodes.computer_3.geometry}
          material={materials["GREEN PLASTIC"]}
        />
        <mesh geometry={nodes.computer_4.geometry} material={materials.COMP2} />
        <mesh
          geometry={nodes.computer_5.geometry}
          material={materials["BLACK MATTE2"]}
        />
        <mesh geometry={nodes.computer_6.geometry} material={materials.KEY1} />
      </group>
    </group>
  );
}

useGLTF.preload("./models/first-pc.glb");
