import Head from "next/head";
import Loginbtn from "./loginbtn";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="text-gray-500">hi</h2>
        <Loginbtn />
      </main>
    </>
  );
}
